version: '3'

services:
  web:
    build:
      context: ./backend
    container_name: django_app
    restart: always
    env_file:
      - ./backend/.env
    expose:
      - "8000"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web