# Generated by Django 5.0.6 on 2024-06-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('net_revenue', models.FloatField()),
                ('net_profit', models.FloatField()),
                ('net_worth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10)),
                ('indicator_name', models.CharField(max_length=100)),
                ('indicator_value', models.CharField(max_length=100)),
            ],
        ),
    ]
